/* ================================================================
   APP.JS — Instantly loads 100 posts from ALL_POSTS (posts-data.js)
   Categories: JavaScript, Playwright, MCP
   ================================================================ */

const STORAGE_KEY = "jsPlaywrightMcpBlogPosts";
const CONTENT_VERSION = 9;

const form = document.getElementById("post-form");
const postIdInput = document.getElementById("post-id");
const titleInput = document.getElementById("title");
const categoryInput = document.getElementById("category");
const tagsInput = document.getElementById("tags");
const excerptInput = document.getElementById("excerpt");
const contentInput = document.getElementById("content");
const coverImageInput = document.getElementById("cover-image");
const coverPreview = document.getElementById("cover-preview");
const clearBtn = document.getElementById("clear-btn");
const postsContainer = document.getElementById("posts");
const searchInput = document.getElementById("search");
const filterCategory = document.getElementById("filter-category");
const exportBtn = document.getElementById("export-btn");
const importBtn = document.getElementById("import-btn");
const importFile = document.getElementById("import-file");
const template = document.getElementById("post-card-template");
const viewer = document.getElementById("viewer");
const viewerContent = document.getElementById("viewer-content");
let currentCoverImageData = "";
let currentLevelFilter = "All";

/* ── Helpers ────────────────────────────────────────────── */

function uid() {
  return `${Date.now()}-${Math.floor(Math.random() * 100000)}`;
}

function loadPosts() {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function savePosts(posts) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(posts));
}

function formatDate(iso) {
  return new Date(iso).toLocaleString();
}

/* ── Load all 100 posts instantly ──────────────────────── */

function loadAllPostsFromNotes() {
  const existing = loadPosts();

  // Reload when source content version changes or autogenerated data is incomplete.
  const autoGenerated = existing.filter((p) => p && p.autoGenerated);
  const sourceMatches = autoGenerated.every((p, i) => {
    const src = ALL_POSTS[i];
    if (!src) return false;
    return p.title === src.title && p.excerpt === src.excerpt && p.content === src.content;
  });
  const hasCurrentVersion =
    autoGenerated.length === ALL_POSTS.length &&
    autoGenerated.every((p) => p.contentVersion === CONTENT_VERSION && typeof p.content === "string" && p.content.length > 200) &&
    sourceMatches;

  if (hasCurrentVersion) {
    return;
  }

  // Preserve manual posts and regenerate only the note-backed posts.
  const manualPosts = existing.filter((p) => !p.autoGenerated);
  const now = Date.now();
  const regeneratedPosts = ALL_POSTS.map((src, i) => ({
    id: `note-${src.id}-${now}`,
    title: src.title,
    category: src.category,
    tags: src.tags,
    excerpt: src.excerpt,
    coverImageData: "",
    content: src.content,
    sourceUrl: src.sourceUrl || "",
    createdAt: src.createdAt || new Date(now - i * 60000).toISOString(),
    level: src.level || "beginner",
    autoGenerated: true,
    contentVersion: CONTENT_VERSION,
  }));

  savePosts([...manualPosts, ...regeneratedPosts]);
}

/* ── Filter & Search ───────────────────────────────────── */

function currentFilters() {
  return {
    search: searchInput.value.trim().toLowerCase(),
    category: filterCategory.value,
  };
}

function filteredPosts(posts) {
  const { search, category } = currentFilters();
  return posts
    .filter((post) => {
      const categoryMatch = category === "All" || post.category === category;
      const levelMatch = currentLevelFilter === "All" || (post.level || "beginner") === currentLevelFilter;
      const searchMatch =
        search.length === 0 ||
        post.title.toLowerCase().includes(search) ||
        post.excerpt.toLowerCase().includes(search) ||
        post.content.toLowerCase().includes(search) ||
        post.tags.join(" ").toLowerCase().includes(search);
      return categoryMatch && levelMatch && searchMatch;
    })
    .sort((a, b) => {
      // Sort by level order: beginner → intermediate → advanced
      const levelOrder = { beginner: 0, intermediate: 1, advanced: 2 };
      const levelDiff = (levelOrder[a.level] || 0) - (levelOrder[b.level] || 0);
      if (levelDiff !== 0) return levelDiff;
      return new Date(b.createdAt) - new Date(a.createdAt);
    });
}

/* ── Markdown to HTML Renderer ─────────────────────────── */

function escapeHtml(text) {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function markdownToHtml(markdown) {
  const escaped = escapeHtml(markdown || "");

  // Fenced code blocks
  const fenced = escaped.replace(/```(\w*)\n?([\s\S]*?)```/g, (_m, lang, code) => {
    const cls = lang ? ` class="lang-${lang}"` : "";
    return `<pre><code${cls}>${code.trim()}</code></pre>`;
  });

  // Headings with auto-generated IDs for TOC linking
  const headings = fenced
    .replace(/^###\s+(.*)$/gm, (_m, text) => {
      const id = text.replace(/[^a-zA-Z0-9\s]/g, "").trim().replace(/\s+/g, "-").toLowerCase();
      return `<h3 id="${id}">${text}</h3>`;
    })
    .replace(/^##\s+(.*)$/gm, (_m, text) => {
      const id = text.replace(/[^a-zA-Z0-9\s]/g, "").trim().replace(/\s+/g, "-").toLowerCase();
      return `<h2 id="${id}">${text}</h2>`;
    })
    .replace(/^#\s+(.*)$/gm, "<h1>$1</h1>");

  // Inline formatting
  const bold = headings.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
  const italic = bold.replace(/\*(.+?)\*/g, "<em>$1</em>");
  const inlineCode = italic.replace(/`([^`]+)`/g, "<code>$1</code>");

  // Links
  const links = inlineCode.replace(
    /\[(.+?)\]\((https?:\/\/[^\s)]+)\)/g,
    '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>'
  );

  // Tables (simple pipe tables)
  const withTables = links.replace(
    /(?:^|\n)(\|.+\|)\n(\|[-| :]+\|)\n((?:\|.+\|\n?)+)/g,
    (_m, headerRow, _sep, bodyRows) => {
      const headers = headerRow.split("|").filter(Boolean).map(h => `<th>${h.trim()}</th>`).join("");
      const rows = bodyRows.trim().split("\n").map(row => {
        const cells = row.split("|").filter(Boolean).map(c => `<td>${c.trim()}</td>`).join("");
        return `<tr>${cells}</tr>`;
      }).join("");
      return `<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>`;
    }
  );

  // Lists
  const withLists = withTables.replace(/(?:^|\n)(-\s+.+(?:\n-\s+.+)*)/g, (chunk) => {
    const items = chunk
      .trim()
      .split("\n")
      .map((line) => line.replace(/^-\s+/, "").trim())
      .filter(Boolean)
      .map((item) => `<li>${item}</li>`)
      .join("");
    return `<ul>${items}</ul>`;
  });

  // Blockquotes
  const withQuotes = withLists.replace(/(?:^|\n)&gt;\s+(.+)/g, '<blockquote>$1</blockquote>');

  return withQuotes
    .split(/\n\n+/)
    .map((block) => {
      const trimmed = block.trim();
      if (!trimmed) return "";
      if (/^<h[1-3]>|^<ul>|^<pre>|^<table>|^<blockquote>/.test(trimmed)) return trimmed;
      return `<p>${trimmed.replace(/\n/g, "<br>")}</p>`;
    })
    .join("\n");
}

/* ── Post Viewer ───────────────────────────────────────── */

function generateToc(markdown) {
  const headings = [];
  const lines = (markdown || "").split("\n");
  for (const line of lines) {
    const h2Match = line.match(/^##\s+(.+)$/);
    const h3Match = line.match(/^###\s+(.+)$/);
    if (h3Match) {
      const text = h3Match[1].trim();
      const id = text.replace(/[^a-zA-Z0-9\s]/g, "").trim().replace(/\s+/g, "-").toLowerCase();
      headings.push({ level: 3, text, id });
    } else if (h2Match) {
      const text = h2Match[1].trim();
      const id = text.replace(/[^a-zA-Z0-9\s]/g, "").trim().replace(/\s+/g, "-").toLowerCase();
      headings.push({ level: 2, text, id });
    }
  }
  if (headings.length < 3) return "";
  const items = headings.map((h) => {
    const indent = h.level === 3 ? " toc-indent" : "";
    return `<li class="toc-item${indent}"><a href="#${h.id}" class="toc-link">${escapeHtml(h.text)}</a></li>`;
  }).join("");
  return `<nav class="table-of-contents"><h3 class="toc-title">📋 Table of Contents</h3><ul class="toc-list">${items}</ul></nav>`;
}

function viewPost(post) {
  const level = (post.level || "beginner").toLowerCase();
  const levelLabel = { beginner: "🌱 Beginner", intermediate: "⭐ Intermediate", advanced: "🚀 Advanced / Architect" };
  const toc = generateToc(post.content);
  const contentHtml = markdownToHtml(post.content);
  const readTime = Math.max(1, Math.ceil((post.content || "").split(/\s+/).length / 200));

  viewerContent.innerHTML = `
    <div class="viewer-header">
      <span class="category cat-${post.category.toLowerCase()}">${escapeHtml(post.category)}</span>
      <span class="level-badge level-${level}">${levelLabel[level] || level}</span>
      <span class="read-time">📖 ${readTime} min read</span>
      <time>${escapeHtml(formatDate(post.createdAt))}</time>
    </div>
    <h2>${escapeHtml(post.title)}</h2>
    <p class="viewer-excerpt">${escapeHtml(post.excerpt)}</p>
    <div class="viewer-tags">${post.tags.map((t) => `<span class="tag">#${escapeHtml(t)}</span>`).join(" ")}</div>
    <!-- In-article ad (highest CPM - user is engaged reading) -->
    <div class="ad-slot ad-article">
      <ins class="adsbygoogle" style="display:block; text-align:center;" data-ad-client="ca-pub-2441085120272132" data-ad-slot="ARTICLE_SLOT_ID" data-ad-format="auto" data-full-width-responsive="true"></ins>
    </div>
    ${toc}
    <div class="post-body">${contentHtml}</div>
    <!-- Bottom of article ad -->
    <div class="ad-slot ad-article-bottom">
      <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2441085120272132" data-ad-slot="ARTICLE_BOTTOM_ID" data-ad-format="auto" data-full-width-responsive="true"></ins>
    </div>
  `;

  // Smooth scroll for TOC links
  viewerContent.querySelectorAll(".toc-link").forEach((link) => {
    link.addEventListener("click", (e) => {
      e.preventDefault();
      const targetId = link.getAttribute("href").slice(1);
      const target = viewerContent.querySelector("#" + CSS.escape(targetId));
      if (target) target.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  });

  try { (window.adsbygoogle = window.adsbygoogle || []).push({}); (window.adsbygoogle = window.adsbygoogle || []).push({}); } catch(e) {}
  viewer.showModal();
}

/* ── Rendering ─────────────────────────────────────────── */

function renderEmpty() {
  postsContainer.innerHTML =
    '<p class="empty-state">No posts match this filter. Try another category or search term.</p>';
}

function renderPosts() {
  const posts = filteredPosts(loadPosts());
  postsContainer.innerHTML = "";

  if (posts.length === 0) {
    renderEmpty();
    return;
  }

  // Show count
  const countEl = document.createElement("p");
  countEl.className = "post-count";
  countEl.textContent = `Showing ${posts.length} post${posts.length !== 1 ? "s" : ""}`;
  postsContainer.appendChild(countEl);

  posts.forEach((post, index) => {
    const fragment = template.content.cloneNode(true);
    const card = fragment.querySelector(".post-card");
    const cardCover = fragment.querySelector(".card-cover");

    card.style.animationDelay = `${Math.min(index * 20, 200)}ms`;
    if (post.coverImageData) {
      cardCover.src = post.coverImageData;
      cardCover.classList.remove("hidden");
    }
    const catSpan = fragment.querySelector(".category");
    catSpan.textContent = post.category;
    catSpan.className = `category cat-${post.category.toLowerCase()}`;

    // Add level badge
    const metaRow = fragment.querySelector(".meta-row");
    const levelSpan = document.createElement("span");
    const postLevel = (post.level || "beginner").toLowerCase();
    const levelEmojis = { beginner: "🌱", intermediate: "⭐", advanced: "🚀" };
    levelSpan.className = `level-badge level-${postLevel}`;
    levelSpan.textContent = `${levelEmojis[postLevel] || ""} ${postLevel.charAt(0).toUpperCase() + postLevel.slice(1)}`;
    metaRow.insertBefore(levelSpan, metaRow.querySelector("time"));

    fragment.querySelector("time").textContent = formatDate(post.createdAt);
    fragment.querySelector("h3").textContent = post.title;
    fragment.querySelector(".excerpt").textContent = post.excerpt;

    const tags = fragment.querySelector(".tags");
    post.tags.forEach((tag) => {
      const span = document.createElement("span");
      span.className = "tag";
      span.textContent = `#${tag}`;
      tags.appendChild(span);
    });

    fragment.querySelector(".read-btn").addEventListener("click", () => viewPost(post));
    fragment.querySelector(".edit-btn").addEventListener("click", () => editPost(post));
    fragment.querySelector(".delete-btn").addEventListener("click", () => deletePost(post.id));

    postsContainer.appendChild(fragment);

    // Insert in-feed ad every 5 posts
    if ((index + 1) % 5 === 0 && index < posts.length - 1) {
      const adDiv = document.createElement("div");
      adDiv.className = "ad-slot ad-infeed";
      adDiv.innerHTML = `<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2441085120272132" data-ad-slot="INFEED_SLOT_ID" data-ad-format="fluid" data-ad-layout-key="-6t+ed+2i-1n-4w"></ins>`;
      postsContainer.appendChild(adDiv);
      try { (window.adsbygoogle = window.adsbygoogle || []).push({}); } catch(e) {}
    }
  });
}

/* ── Form: Create / Edit / Delete ──────────────────────── */

function resetForm() {
  postIdInput.value = "";
  currentCoverImageData = "";
  coverPreview.src = "";
  coverPreview.classList.add("hidden");
  form.reset();
}

function editPost(post) {
  postIdInput.value = post.id;
  titleInput.value = post.title;
  categoryInput.value = post.category;
  tagsInput.value = post.tags.join(", ");
  excerptInput.value = post.excerpt;
  contentInput.value = post.content;
  currentCoverImageData = post.coverImageData || "";
  if (currentCoverImageData) {
    coverPreview.src = currentCoverImageData;
    coverPreview.classList.remove("hidden");
  } else {
    coverPreview.classList.add("hidden");
  }
  titleInput.focus();
}

function deletePost(id) {
  const posts = loadPosts().filter((p) => p.id !== id);
  savePosts(posts);
  renderPosts();
}

form.addEventListener("submit", (event) => {
  event.preventDefault();

  const post = {
    id: postIdInput.value || uid(),
    title: titleInput.value.trim(),
    category: categoryInput.value,
    tags: tagsInput.value
      .split(",")
      .map((t) => t.trim())
      .filter(Boolean),
    excerpt: excerptInput.value.trim(),
    coverImageData: currentCoverImageData,
    content: contentInput.value.trim(),
    sourceUrl: "",
    createdAt: new Date().toISOString(),
    contentVersion: CONTENT_VERSION,
  };

  const posts = loadPosts();
  const existingIndex = posts.findIndex((p) => p.id === post.id);
  if (existingIndex >= 0) {
    post.createdAt = posts[existingIndex].createdAt;
    posts[existingIndex] = post;
  } else {
    posts.push(post);
  }

  savePosts(posts);
  resetForm();
  renderPosts();
});

/* ── Event Listeners ───────────────────────────────────── */

clearBtn.addEventListener("click", resetForm);
searchInput.addEventListener("input", renderPosts);
filterCategory.addEventListener("change", renderPosts);

coverImageInput.addEventListener("change", async () => {
  const file = coverImageInput.files?.[0];
  if (!file) {
    currentCoverImageData = "";
    coverPreview.classList.add("hidden");
    return;
  }
  const reader = new FileReader();
  reader.onload = () => {
    currentCoverImageData = String(reader.result || "");
    if (currentCoverImageData) {
      coverPreview.src = currentCoverImageData;
      coverPreview.classList.remove("hidden");
    }
  };
  reader.readAsDataURL(file);
});

exportBtn.addEventListener("click", () => {
  const posts = loadPosts();
  const blob = new Blob([JSON.stringify(posts, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `blog-posts-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
});

importBtn.addEventListener("click", () => importFile.click());

importFile.addEventListener("change", async () => {
  const file = importFile.files?.[0];
  if (!file) return;
  try {
    const text = await file.text();
    const parsed = JSON.parse(text);
    if (!Array.isArray(parsed)) throw new Error("Invalid JSON format");
    const cleaned = parsed
      .filter((p) => p && typeof p.title === "string" && typeof p.content === "string")
      .map((p) => ({
        id: p.id || uid(),
        title: String(p.title),
        category: ["JavaScript", "TypeScript", "Playwright", "MCP", "TOSCA", "Both"].includes(p.category) ? p.category : "Both",
        tags: Array.isArray(p.tags) ? p.tags.map(String) : [],
        excerpt: String(p.excerpt || ""),
        coverImageData: String(p.coverImageData || ""),
        content: String(p.content),
        sourceUrl: String(p.sourceUrl || ""),
        createdAt: p.createdAt ? String(p.createdAt) : new Date().toISOString(),
        contentVersion: CONTENT_VERSION,
      }));
    savePosts(cleaned);
    renderPosts();
  } catch (error) {
    alert(`Import failed: ${error.message || error}`);
  } finally {
    importFile.value = "";
  }
});

/* ── Initialize: Load all posts instantly ──────────── */
loadAllPostsFromNotes();
renderPosts();

/* ── Level Filter Navigation ───────────────────────── */
const pathNav = document.getElementById("learning-path-nav");
if (pathNav) {
  pathNav.addEventListener("click", (e) => {
    const btn = e.target.closest(".path-btn");
    if (!btn) return;
    pathNav.querySelectorAll(".path-btn").forEach((b) => b.classList.remove("active"));
    btn.classList.add("active");
    currentLevelFilter = btn.dataset.level || "All";
    renderPosts();
  });
}
